model: llm

framework: pytorch

workflow:
 generate_data: False
 train: True

dataset:
 num_files_train: 1024
 num_samples_per_file: 55000
 record_length: 2500
 data_folder: data/llm
 format: tfrecord_llm

train: 
 computation_time: 0.435
 epochs: 1
 
reader:
 data_loader: dali
 read_threads: 8
 computation_threads: 8
 batch_size: 400
 dont_use_mmap: True
